config/routes.rb
AjaxRails::Application.routes.draw do
  get  "pages/index"
  post "pages/mensagem"
  get "pages/mensagem_dois"

  root :to => 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def mensagem
    respond_to do|format|
      format.js
    end
  end

  def mensagem_dois
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_ola_ajax.html.erb
<p>
  <span>Inserido via AJAX</span><br/>
  =]
</p>

app/views/pages/index.html.erb
<h1>Testes com Ajax</h1>
<p>
  <%= form_for "teste", :url => pages_mensagem_path(:format => :js), :remote => true do |a|%>
    Digite um numero:<br/>
    <%= a.text_field :campo_texto, :id => :campo_texto %><br/>
    <%= a.submit "Teste Ajax" %>
  <% end %>
  <div id="conteudo">
  </div>
</p>
<script type="text/javascript">
  $("#campo_texto").on("blur", function() {
    $.ajax({
      url: "pages/mensagem_dois",
      type: "GET",
      data: {
        "linhas": $("#campo_texto").val()
      }
    }).done(function(data){
      $("#conteudo").empty();
      $("#conteudo").append(data);
    });
  });
</script>

app/views/pages/mensagem.js.erb
$("#conteudo").empty();
$("#conteudo").append("<%= escape_javascript(render 'pages/ola_ajax') %>");

app/views/pages/mensagem_dois.html.erb
<p>
  <% linhas = params[:linhas] if params[:linhas].to_i > 0 %>
  <%= "<small><i>Exibindo 1 (uma) linha já que não digitou um numero valido.</i></small><br/>".html_safe unless linhas %>
  <% linhas = linhas || 1 %>
  <% (1..linhas.to_i).each do |n| %>
    <%= "Linha #{n}" %><br/>
  <% end%>
</p>